/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    integrations: Integration;
    features: Feature;
    testimonials: Testimonial;
    'pricing-plans': PricingPlan;
    faq: Faq;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
    features: FeaturesSelect<false> | FeaturesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'pricing-plans': PricingPlansSelect<false> | PricingPlansSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    footer: Footer;
    'contact-settings': ContactSetting;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'contact-settings': ContactSettingsSelect<false> | ContactSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL pad (bijv. "over-ons", "contact"). Laat leeg voor homepage.
   */
  slug: string;
  blocks?:
    | (
        | {
            /**
             * Kleine tekst boven de titel (bijv. "Logic4 integratie live")
             */
            badge?: string | null;
            /**
             * Gebruik *tekst* voor gekleurde highlight (bijv. "Slimmer picken met *PickHero*")
             */
            title: string;
            description?: string | null;
            benefits?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            ctaText?: string | null;
            /**
             * Optioneel: laat leeg om het formulier te openen, of vul een URL in
             */
            ctaLink?: string | null;
            image?: (number | null) | Media;
            /**
             * Optioneel: afbeelding of GIF van de mobiele app die over de dashboard afbeelding zweeft
             */
            mobileImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            badge?: string | null;
            /**
             * Gebruik *tekst* voor gekleurde highlight
             */
            title?: string | null;
            subtitle?: string | null;
            /**
             * Selecteer functies om te tonen
             */
            features?: (number | Feature)[] | null;
            /**
             * Optioneel: laat leeg om geen knop te tonen
             */
            ctaText?: string | null;
            /**
             * Optioneel: laat leeg om het formulier te openen
             */
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            badge?: string | null;
            /**
             * Gebruik *tekst* voor gekleurde highlight
             */
            title?: string | null;
            subtitle?: string | null;
            /**
             * Laat leeg om alle integraties te tonen
             */
            integrations?: (number | Integration)[] | null;
            ctaText?: string | null;
            ctaLinkText?: string | null;
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'integrationsTicker';
          }
        | {
            badge?: string | null;
            /**
             * Gebruik *tekst* voor gekleurde highlight
             */
            title?: string | null;
            subtitle?: string | null;
            showFilters?: boolean | null;
            ctaText?: string | null;
            /**
             * Optioneel: laat leeg om het formulier te openen
             */
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'integrationsGrid';
          }
        | {
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            badge?: string | null;
            /**
             * Gebruik *tekst* voor gekleurde highlight
             */
            title?: string | null;
            testimonials?: (number | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            badge?: string | null;
            /**
             * Gebruik *tekst* voor gekleurde highlight
             */
            title?: string | null;
            subtitle?: string | null;
            plans?: (number | PricingPlan)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            /**
             * Gebruik *tekst* voor gekleurde highlight
             */
            title: string;
            description?: string | null;
            ctaText?: string | null;
            /**
             * Optioneel: laat leeg om het formulier te openen
             */
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
        | {
            /**
             * Gebruik *tekst* voor gekleurde highlight
             */
            title: string;
            description?: string | null;
            ctaText?: string | null;
            /**
             * Optioneel: laat leeg om het formulier te openen
             */
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Gebruik *tekst* voor gekleurde highlight
             */
            title?: string | null;
            subtitle?: string | null;
            items?: (number | Faq)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            /**
             * Gebruik *tekst* voor gekleurde highlight
             */
            title?: string | null;
            subtitle?: string | null;
            showFeatured?: boolean | null;
            postsPerPage?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blogList';
          }
        | {
            formTitle?: string | null;
            formDescription?: string | null;
            submitButtonText?: string | null;
            infoTitle?: string | null;
            showMap?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactSection';
          }
        | {
            /**
             * Gebruik *tekst* voor gekleurde highlight
             */
            title?: string | null;
            subtitle?: string | null;
            cards?:
              | {
                  icon:
                    | 'target'
                    | 'zap'
                    | 'heart'
                    | 'users'
                    | 'shield'
                    | 'clock'
                    | 'check'
                    | 'star'
                    | 'truck'
                    | 'package'
                    | 'bar-chart'
                    | 'globe';
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            backgroundColor?: ('none' | 'muted') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'iconCards';
          }
        | {
            /**
             * Gebruik *tekst* voor gekleurde highlight
             */
            title: string;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'intro';
          }
        | {
            /**
             * Gebruik *tekst* voor gekleurde highlight
             */
            title?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'story';
          }
        | {
            badge?: string | null;
            /**
             * Gebruik *tekst* voor gekleurde highlight
             */
            title?: string | null;
            subtitle?: string | null;
            plans?: (number | PricingPlan)[] | null;
            showFilters?: boolean | null;
            showComparison?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingPage';
          }
      )[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Feature {
  id: number;
  title: string;
  icon:
    | 'Zap'
    | 'Package'
    | 'BarChart3'
    | 'Smartphone'
    | 'RefreshCw'
    | 'Shield'
    | 'Building2'
    | 'Clock'
    | 'ShoppingCart'
    | 'Hash'
    | 'Briefcase'
    | 'Code'
    | 'RotateCcw'
    | 'Tag'
    | 'Printer';
  description: string;
  /**
   * Wordt getoond in de popup/modal
   */
  extendedDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  name: string;
  logo: number | Media;
  category?: ('webshop' | 'shipping' | 'accounting' | 'erp' | 'marketplace' | 'other') | null;
  description?: string | null;
  url?: string | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  authorName: string;
  authorRole?: string | null;
  company?: string | null;
  avatar?: (number | null) | Media;
  rating?: number | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans".
 */
export interface PricingPlan {
  id: number;
  name: string;
  description?: string | null;
  priceMonthly?: number | null;
  /**
   * Optioneel: korting voor eerste periode
   */
  priceDiscounted?: number | null;
  isEnterprise?: boolean | null;
  isPopular?: boolean | null;
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  ctaText?: string | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Bijv. "Algemeen", "Prijzen", "Technisch"
   */
  category?: string | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog posts en artikelen
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL-vriendelijke versie van de titel (bijv. "mijn-eerste-blog-post")
   */
  slug: string;
  /**
   * Korte samenvatting voor in overzichten en SEO
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Categorie voor filtering
   */
  category?: ('warehouse' | 'ecommerce' | 'integrations' | 'tips' | 'news' | 'updates') | null;
  author?: string | null;
  featuredImage?: (number | null) | Media;
  readTimeMinutes?: number | null;
  /**
   * Laat leeg voor concepten
   */
  publishedAt?: string | null;
  /**
   * Vink aan om het artikel zichtbaar te maken op de website
   */
  isPublished?: boolean | null;
  seo?: {
    /**
     * Laat leeg om de post titel te gebruiken
     */
    metaTitle?: string | null;
    /**
     * Laat leeg om de samenvatting te gebruiken
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'integrations';
        value: number | Integration;
      } | null)
    | ({
        relationTo: 'features';
        value: number | Feature;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'pricing-plans';
        value: number | PricingPlan;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              badge?: T;
              title?: T;
              description?: T;
              benefits?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              ctaText?: T;
              ctaLink?: T;
              image?: T;
              mobileImage?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              badge?: T;
              title?: T;
              subtitle?: T;
              features?: T;
              ctaText?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        integrationsTicker?:
          | T
          | {
              badge?: T;
              title?: T;
              subtitle?: T;
              integrations?: T;
              ctaText?: T;
              ctaLinkText?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        integrationsGrid?:
          | T
          | {
              badge?: T;
              title?: T;
              subtitle?: T;
              showFilters?: T;
              ctaText?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              badge?: T;
              title?: T;
              testimonials?: T;
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              badge?: T;
              title?: T;
              subtitle?: T;
              plans?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              title?: T;
              description?: T;
              ctaText?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              ctaText?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              subtitle?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        blogList?:
          | T
          | {
              title?: T;
              subtitle?: T;
              showFeatured?: T;
              postsPerPage?: T;
              id?: T;
              blockName?: T;
            };
        contactSection?:
          | T
          | {
              formTitle?: T;
              formDescription?: T;
              submitButtonText?: T;
              infoTitle?: T;
              showMap?: T;
              id?: T;
              blockName?: T;
            };
        iconCards?:
          | T
          | {
              title?: T;
              subtitle?: T;
              cards?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              columns?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        intro?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        story?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        pricingPage?:
          | T
          | {
              badge?: T;
              title?: T;
              subtitle?: T;
              plans?: T;
              showFilters?: T;
              showComparison?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  category?: T;
  description?: T;
  url?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  description?: T;
  extendedDescription?: T;
  image?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  authorRole?: T;
  company?: T;
  avatar?: T;
  rating?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans_select".
 */
export interface PricingPlansSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  priceMonthly?: T;
  priceDiscounted?: T;
  isEnterprise?: T;
  isPopular?: T;
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  ctaText?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  author?: T;
  featuredImage?: T;
  readTimeMinutes?: T;
  publishedAt?: T;
  isPublished?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Beheer het hoofdmenu
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items?:
    | {
        label: string;
        linkType?: ('internal' | 'external' | 'anchor') | null;
        internalLink?: (number | null) | Page;
        /**
         * Volledige URL inclusief https://
         */
        externalUrl?: string | null;
        /**
         * Bijv. "functies" wordt "#functies"
         */
        anchor?: string | null;
        openInNewTab?: boolean | null;
        hasSubmenu?: boolean | null;
        submenuItems?:
          | {
              label: string;
              /**
               * Optionele korte beschrijving onder het label
               */
              description?: string | null;
              linkType?: ('internal' | 'external' | 'anchor') | null;
              internalLink?: (number | null) | Page;
              /**
               * Volledige URL inclusief https://
               */
              externalUrl?: string | null;
              /**
               * Bijv. "functies" wordt "#functies"
               */
              anchor?: string | null;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaText?: string | null;
  loginText?: string | null;
  loginUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Beheer de footer inhoud
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  description?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'linkedin' | 'twitter' | 'facebook' | 'instagram' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Gebruik {{year}} voor het huidige jaar
   */
  copyright?: string | null;
  legalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Beheer contactgegevens voor de website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings".
 */
export interface ContactSetting {
  id: number;
  address?: {
    street?: string | null;
    postalCode?: string | null;
    city?: string | null;
    country?: string | null;
  };
  email?: string | null;
  phone?: string | null;
  /**
   * Bijv. "Ma-Vr: 09:00 - 17:00"
   */
  openingHours?: string | null;
  /**
   * De volledige iframe src URL van Google Maps
   */
  mapsEmbedUrl?: string | null;
  formSettings?: {
    /**
     * E-mailadres waar contactformulier berichten naartoe gestuurd worden
     */
    recipientEmail?: string | null;
    successMessage?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        linkType?: T;
        internalLink?: T;
        externalUrl?: T;
        anchor?: T;
        openInNewTab?: T;
        hasSubmenu?: T;
        submenuItems?:
          | T
          | {
              label?: T;
              description?: T;
              linkType?: T;
              internalLink?: T;
              externalUrl?: T;
              anchor?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  ctaText?: T;
  loginText?: T;
  loginUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings_select".
 */
export interface ContactSettingsSelect<T extends boolean = true> {
  address?:
    | T
    | {
        street?: T;
        postalCode?: T;
        city?: T;
        country?: T;
      };
  email?: T;
  phone?: T;
  openingHours?: T;
  mapsEmbedUrl?: T;
  formSettings?:
    | T
    | {
        recipientEmail?: T;
        successMessage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}